#!/usr/bin/env sh

target_user=$(/usr/bin/whoami)

if [ "$(id -u)" -ne 0 ]; then
  echo "Running with sudo..."
  exec sudo "$0" $target_user "$@"
fi

# Check if the user is specified once the script is run with sudo
if [ $# -eq 1 ]; then
    target_user=$1
fi

AUTOPULL_PATH="$( cd "$( dirname "${BASH_SOURCE}" )" && pwd )"
chmod +x $AUTOPULL_PATH/autopull

ln -s $AUTOPULL_PATH/autopull /usr/local/bin

autopull_repositories_path=$(eval echo ~$target_user)/.autopull_repositories

touch $autopull_repositories_path
chmod 777 $autopull_repositories_path

if ! crontab -u "$target_user" -l | grep -q "$(which autopull)"; then
    (crontab -u "$target_user" -l 2>/dev/null; echo "# AutoPull"; echo "* * * * * $(which autopull) --pull-all") | crontab -u "$target_user" -
fi

echo "Autopull installed. To uninstall, run 'autopull --uninstall'."