#!/usr/bin/env sh

target_user=$(/usr/bin/whoami)

if [ "$(id -u)" -ne 0 ]; then
  echo "Running with sudo..."
  exec sudo "$0" $target_user "$@"
fi

# Check if the user is specified once the script is run with sudo
if [ $# -eq 1 ]; then
    target_user=$1
fi

AUTOPULL_PATH="$( cd "$( dirname "${BASH_SOURCE}" )" && pwd )"
chmod +x $AUTOPULL_PATH/autopull

if [ "$(which autopull)" ]; then
    rm "$(which autopull)"
fi
ln -s $AUTOPULL_PATH/autopull /usr/local/bin

autopull_repositories_path=$(eval echo ~$target_user)/.autopull_repositories
touch $autopull_repositories_path
chmod 777 $autopull_repositories_path

log_file=$(eval echo ~$target_user)/.autopull_logs
touch $log_file
chmod 777 $log_file

if ! crontab -u "$target_user" -l | grep -q "$(which autopull) --pull-all"; then
    (crontab -u "$target_user" -l 2>/dev/null; echo "\n# AutoPull"; echo "* * * * * $(which autopull) --pull-all >> $log_file 2>&1") | crontab -u "$target_user" -
fi

echo "Autopull installed. To uninstall, run 'autopull --uninstall'."