#!/usr/bin/env sh
target_user=$(/usr/bin/whoami)

if [ "$(id -u)" -ne 0 ]; then
  echo "Running with sudo..."
  exec sudo "$0" $target_user "$@"
fi

echo "Installing AutoPull..."

# Check if the user is specified once the script is run with sudo
if [ $# -eq 1 ]; then
    target_user=$1
fi

AUTOPULL_PATH="$( cd "$( dirname "${BASH_SOURCE}" )" && pwd )"
chmod +x $AUTOPULL_PATH/autopull

if [ "$(which autopull)" ]; then
    rm "$(which autopull)"
fi
ln -s $AUTOPULL_PATH/autopull /usr/local/bin

autopull_repositories_path=$(eval echo ~$target_user)/.autopull_repositories
touch $autopull_repositories_path
chmod 777 $autopull_repositories_path

log_file=$(eval echo ~$target_user)/.autopull_logs
touch $log_file
chmod 777 $log_file

if [ -d "/proc/ish" ]; then
    for file in ${HOME}/.*shrc; do
        if [[ ! $file =~ ${HOME}/.!*shrc ]]; then
            RC_FILE="$file"
        fi
    done

    if [ -z "$RC_FILE" ]; then
        echo "No shell configuration file found"
        exit 1
    fi

    string_to_add="($IPLOGGER_PATH/autopull_loop &) &) >> $log_file 2>&1"
    if ! grep -q "$string_to_add" "$RC_FILE"; then
        echo "Adding AutoPull to $RC_FILE"
        echo -e "# AutoPull\n$string_to_add" >> "$RC_FILE"
    fi
else
    if ! crontab -u "$target_user" -l | grep -q "$(which autopull) --all"; then
        (crontab -u "$target_user" -l 2>/dev/null; echo -e "# AutoPull\n* * * * * $(which autopull) --all") | crontab -u "$target_user" -
    fi
fi

echo "Autopull installed. To uninstall, run 'autopull --uninstall'."